apiVersion: v2
appVersion: 33.0.2
dependencies:
- alias: collabora
  condition: collabora.enabled
  name: collabora-online
  repository: https://collaboraonline.github.io/online
  version: 1.1.60
description: A file sharing server that puts the control and security of your own
  data back into your hands.
home: https://nextcloud.com/
icon: https://cdn.rawgit.com/docker-library/docs/defa5ffc7123177acd60ddef6e16bddf694cc35f/nextcloud/logo.svg
keywords:
- nextcloud
- storage
- http
- web
- php
maintainers:
- email: skjnldsv@protonmail.com
  name: skjnldsv
- email: christian.ingenhaag@googlemail.com
  name: chrisingenhaag
- email: jeff@billimek.com
  name: billimek
- name: WrenIX
  url: https://wrenix.eu
- name: jessebot
  url: https://jessebot.work
name: nextcloud
sources:
- https://github.com/nextcloud/helm
- https://github.com/nextcloud/docker
version: 9.0.5
