apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secret
    namespace: nextcloud
stringData:
    adminUsername: ENC[AES256_GCM,data:wW2DJUQ=,iv:ADw7T5IQKPsAWwWg5H+kmsSNm8UHf6iCRYqih6Idybw=,tag:wrFrIX6xjHiGYrmEfHsFvA==,type:str]
    adminPassword: ENC[AES256_GCM,data:PPckaj2W6QdW,iv:5rEd+LcrFU01x+yOmoOmN7lsSDfXhgw/yBvH27oNlSk=,tag:oA2VwEaWeOeiqQAT96mFNA==,type:str]
sops:
    age:
        - recipient: age1tnc40zw8l5f2vh9qgnj4q3vcx74xpcgypwcvlfnw2x6j0yat4p8q4pc2q0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6REpFLy9aaTNlL0YyQTVI
            b3MrU1RIUnE1QkRGOVM5a1YrcG12R3daYlhzCk5iWElRTW5Vay8wYWs1TFFHd2Q2
            eEVPN0M1S1BFMTk4aFJpUGdQTFllUmMKLS0tIG1YNzRObU5rUldLdXdmTk9Yc1Rl
            U2RTRWc3RnBELzVtMzlKVzlOa2ZoWUkK/cUQq6VtLQhZQ6Lncqkpmfo8lVhXkrCb
            tb9cruZKkAFisXESKF6QOcQOBDAfftjlF4/bIhi88bPVmeC16F/y+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T16:55:41Z"
    mac: ENC[AES256_GCM,data:e+qfS9A/QrJQCI2FST2uWXx/DwY6Rsjc4gYJaHlLRpXaCFZnEC/Te4Hd98D1rwcadBTXIwwilO9KpxFW9mGW9o+nz1TTRgAU2FL776ErMsDF33w35eE0niJB6l6NgjeoKTBOHQqlPW+lMUQHmN2+mXm0gUh8EYcfADBnoFi2QKM=,iv:go/W7wnz5JlV5pXbSGVDr5HhTFa6xDQffOPVOy694Os=,tag:LNDqc8w+dtNg4XMy5TeNiQ==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.12.2
