apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: infra-vault
spec:
  interval: 10m
  chart:
    spec:
      chart: ./my-home-cluster/infra/vault
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      valuesFiles:
        - values.yaml
      interval: 10s