apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-pv-volume
  namespace: app-mlflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
    storageClassName: "local-path" 
