{{- $ingress := .Values.ingress -}}
{{- $fullname := .Release.fullname -}}
{{- if $ingress.enabled }}
{{- $newAPIversion := .Capabilities.APIVersions.Has "networking.k8s.io/v1" }}
{{- if $newAPIversion }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "vaultwarden.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: vaultwarden
    {{- include "vaultwarden.labels" . | nindent 4 }}
    {{- range $key, $value := $ingress.labels }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
  {{- with $ingress.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $ingress.class }}
  ingressClassName: {{ $ingress.class | quote }}
  {{- end }}
  {{- if $ingress.tls }}
  tls:
    - hosts:
        - {{ $ingress.hostname | quote }}
      secretName: {{ $ingress.tlsSecret }}
  {{- end }}
  rules:
    - host: {{ $ingress.hostname | quote }}
      http:
        paths:
        - path: {{ $ingress.path }}
          pathType: {{ $ingress.pathType }}
          backend:
            service:
              name: {{ include "vaultwarden.fullname" . }}
              port:
                name: "http"
{{- end }}
