apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-ca
  namespace: app-nextcloud
data:
  vault-ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIBnDCCAUKgAwIBAgIUHaFyUHX10Rlty8WKwFTQ2O8lulkwCgYIKoZIzj0EAwIw
    LDEQMA4GA1UEChMHaG9tZWxhYjEYMBYGA1UEAxMPSG9tZWxhYiBSb290IENBMB4X
    DTI2MDYxMjEzNDM1NFoXDTM2MDYwOTEzNDM1NFowLDEQMA4GA1UEChMHaG9tZWxh
    YjEYMBYGA1UEAxMPSG9tZWxhYiBSb290IENBMFkwEwYHKoZIzj0CAQYIKoZIzj0D
    AQcDQgAE+WHsZfmWKbgu0iNkpons13bBvIninSg6o5Jta8xHIXt4O5mZMHOI3QSd
    Ky/kANOymO4rEvB8DDRmI1dOOCVTBqNCMEAwDgYDVR0PAQH/BAQDAgKkMA8GA1Ud
    EwEB/wQFMAMBAf8wHQYDVR0OBBYEFEOEoOyPpM3YaX0nCslstXbtOhcTMAoGCCqG
    SM49BAMCA0gAMEUCIQDjMS4NMzf1Ve9e1QyMEq1m7ZouHtll/N7Z+ODTlzzifAIg
    Yh9eTWYTw06eRDDYiU77bssYDl9n+q4Td8fZ4Mw9hZQ=
    -----END CERTIFICATE-----
