apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-ca
  namespace: app-nextcloud
data:
  vault-ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIBdzCCAR2gAwIBAgIBADAKBggqhkjOPQQDAjAjMSEwHwYDVQQDDBhrM3Mtc2Vy
    dmVyLWNhQDE3Nzc3MTg0MjMwHhcNMjYwNTAyMDk0MDIzWhcNMzYwNDI5MDk0MDIz
    WjAjMSEwHwYDVQQDDBhrM3Mtc2VydmVyLWNhQDE3Nzc3MTg0MjMwWTATBgcqhkjO
    PQIBBggqhkjOPQMBBwNCAAQri8PcPIc7m6hZEUAXBkZ0oGJcqWojA8Gqfo4VybaO
    wxWwNAu0oEAEdUshpPDh1Q7LMtXflt6eQYhppXk1Tp2xo0IwQDAOBgNVHQ8BAf8E
    BAMCAqQwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUCmDe9EQkJbNviyHvo7qv
    Ltt+6ZkwCgYIKoZIzj0EAwIDSAAwRQIgQq5bArisJQ9ytInp3He4nGmuWiXts7rU
    wgIXX4nIpF8CIQCsKqknDDGoOgaVWTxsrB/46Iiuh52d0RmYiLydOsJdiQ==
    -----END CERTIFICATE-----