apiVersion: batch/v1
kind: CronJob
metadata:
  name: nextcloud-db-backup
spec:
  schedule: "0 9 * * *"  
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: db-backup
            image: efrecon/sqlite-backup:2.0.0
            env:
              - name: ADMIN_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: nextcloud-secret
                    key: adminUsername
              - name: ADMIN_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: nextcloud-secret
                    key: adminPassword           
            command: ["/bin/bash", "-c", "/usr/local/bin/backup.sh"]
            volumeMounts:
            - name: backup-dir
              mountPath: /backup 
          volumes:
            - name: backup-dir
              hostPath:
                path: /Users/rizaorduhani/k3s-backups  
                type: DirectoryOrCreate
