apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-store
  namespace: app-nextcloud
spec:
  provider:
    vault:
      server: "https://vault.kube.home"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: kubernetes
          role: nextcloud-role
          serviceAccountRef:
            name: nextcloud-serviceaccount 

---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud-secret
  namespace: app-nextcloud
spec:
  refreshInterval: "24h" 
  secretStoreRef:
    name: vault-store 
    kind: SecretStore
  target:
    name: nextcloud-secret 
    creationPolicy: "Owner"
  dataFrom:
  - extract:
      key: "prod/nextcloud"