---
global:
  nodeSelector:
    kubernetes.io/hostname: server2
  tolerations: []
  topologySpreadConstraints: []
  affinity: {}
  podLabels: {}
  podAnnotations: {}
  imagePullSecrets: []
  repository: ""

replicaCount: 1

# -- If set, install and upgrade CRDs through helm chart.
installCRDs: true

crds:
  createClusterExternalSecret: true
  createClusterSecretStore: true
  createSecretStore: true
  createClusterGenerator: true
  createClusterPushSecret: true
  createPushSecret: true

imagePullSecrets: []
nameOverride: infra-external-secrets
fullnameOverride: infra-external-secrets
namespaceOverride: ""

commonLabels: {}

# -- If true, external-secrets will perform leader election between instances
leaderElect: false

# -- If true, the operator will process cluster external secret
processClusterExternalSecret: true
processClusterPushSecret: true
processClusterStore: true
processSecretStore: true
processClusterGenerator: true
processPushSecret: true

# -- Specifies whether an external secret operator deployment be created
createOperator: true

log:
  level: info
  timeEncoding: epoch

serviceAccount:
  create: true
  automount: true
  annotations: {}
  extraLabels: {}
  name: ""

rbac:
  create: true
  serviceAccountTokenCreate: true
  servicebindings:
    create: true
  aggregateToView: true
  aggregateToEdit: true

extraEnv: []
extraArgs: {}
extraVolumes: []
extraVolumeMounts: []
extraInitContainers: []
extraContainers: []

# -- Extra Kubernetes objects to deploy with the helm chart
extraObjects: []

deploymentAnnotations: {}
strategy: {}
podAnnotations: {}
podLabels: {}

podSecurityContext:
  enabled: true

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  enabled: true
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: RuntimeDefault

resources: {}

serviceMonitor:
  enabled: false
  namespace: ""
  additionalLabels: {}
  interval: 30s
  scrapeTimeout: 25s
  honorLabels: false
  metricRelabelings: []
  relabelings: []

metrics:
  listen:
    port: 8080
    auth:
      enabled: false
    secure:
      enabled: false
      certDir: /etc/tls
      certFile: /etc/tls/tls.crt
      keyFile: /etc/tls/tls.key

  service:
    enabled: false
    port: 8080
    annotations: {}

grafanaDashboard:
  enabled: false
  sidecarLabel: "grafana_dashboard"
  sidecarLabelValue: "1"
  annotations: {}
  extraLabels: {}

livenessProbe:
  enabled: false
  spec:
    address: ""
    port: 8082
    timeoutSeconds: 5
    failureThreshold: 5
    periodSeconds: 10
    successThreshold: 1
    initialDelaySeconds: 10
    httpGet:
      port: live
      path: /healthz

readinessProbe:
  enabled: false
  spec:
    timeoutSeconds: 5
    failureThreshold: 3
    periodSeconds: 10
    successThreshold: 1
    initialDelaySeconds: 10
    httpGet:
      port: live
      path: /readyz

nodeSelector: {}
tolerations: []
topologySpreadConstraints: []
affinity: {}
priorityClassName: ""

image:
  repository: ghcr.io/external-secrets/external-secrets
  pullPolicy: IfNotPresent
  tag: ""

webhook:
  annotations: {}
  create: true
  certCheckInterval: "5m"
  replicaCount: 1

  log:
    level: info
    timeEncoding: epoch

  certDir: /tmp/certs
  failurePolicy: Fail
  hostNetwork: false

  image:
    repository: ghcr.io/external-secrets/external-secrets
    pullPolicy: IfNotPresent
    tag: ""

  imagePullSecrets: []
  port: 10250

  serviceAccount:
    create: true
    automount: true
    annotations: {}
    extraLabels: {}
    name: ""

  nodeSelector: {}
  tolerations: []
  topologySpreadConstraints: []
  affinity: {}
  strategy: {}
  priorityClassName: ""

  metrics:
    listen:
      port: 8080
      auth:
        enabled: false
      secure:
        enabled: false
        certDir: /etc/tls
        certFile: /etc/tls/tls.crt
        keyFile: /etc/tls/tls.key

    service:
      enabled: false
      port: 8080
      annotations: {}

  livenessProbe:
    enabled: false
    port: 8081
    timeoutSeconds: 5
    failureThreshold: 5
    periodSeconds: 10
    successThreshold: 1
    initialDelaySeconds: 10

  readinessProbe:
    enabled: true
    address: ""
    port: 8081
    timeoutSeconds: 5
    failureThreshold: 3
    periodSeconds: 5
    successThreshold: 1
    initialDelaySeconds: 20

  extraEnv: []
  extraArgs: {}
  extraInitContainers: []
  extraVolumes: []
  extraVolumeMounts: []
  secretAnnotations: {}
  deploymentAnnotations: {}
  podAnnotations: {}
  podLabels: {}

  podSecurityContext:
    enabled: true

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    enabled: true
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault

  resources: {}

  validatingWebhookConfiguration:
    namespaceSelector:
      matchExpressions:
        - key: "external-secrets.io/webhook"
          operator: "NotIn"
          values:
            - "disable"

  mutatingWebhookConfiguration:
    namespaceSelector: {}

  service:
    enabled: true
    annotations: {}
    labels: {}
    type: ClusterIP
