apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: external-secrets-webhook
  namespace: infra-external-secrets
spec:
  secretName: external-secrets-webhook-tls
  duration: 2160h
  renewBefore: 360h
  dnsNames:
    - infra-external-secrets-webhook.infra-external-secrets.svc
    - infra-external-secrets-webhook.infra-external-secrets.svc.cluster.local
  issuerRef:
    name: homelab-ca
    kind: ClusterIssuer
