## Vaultwarden configuration
## Instruction: when adding a new value, follow https://github.com/dani-garcia/vaultwarden/blob/main/.env.template as much as possible.

## @section Kubernetes settings
image:
  registry: docker.io
  repository: vaultwarden/server
  tag: "1.36.0-alpine"
  pullPolicy: IfNotPresent
  pullSecrets: []
  extraSecrets: []
  extraVars: []
  extraVarsCM: ""
  extraVarsSecret: ""

## @param replicas Number of deployment replicas
replicas: 1

## @param fullnameOverride String to override the application name.
fullnameOverride: ""

## @param resourceType Can be either Deployment or StatefulSet
resourceType: ""

## @param commonAnnotations Annotations for the deployment or statefulset
commonAnnotations: {}

## @param configMapAnnotations Add extra annotations to the configmap
configMapAnnotations: {}

## @param podAnnotations Add extra annotations to the pod
podAnnotations: {}

## @param commonLabels Additional labels for the deployment or statefulset
commonLabels: {}

## @param podLabels Add extra labels to the pod
podLabels: {}

## @param initContainers extra init containers for initializing the vaultwarden instance
initContainers: []

## @param sidecars extra containers running alongside the vaultwarden instance
sidecars: []

## @param extraVolumes Optionally specify extra list of additional volumes
extraVolumes: []

## @param extraVolumeMounts Optionally specify extra list of additional volumeMounts
extraVolumeMounts: []

## @param nodeSelector Node labels for pod assignment
nodeSelector: 
  kubernetes.io/hostname: server2

## @param affinity Affinity for pod assignment
affinity: {}

## @param tolerations Tolerations for pod assignment
tolerations: []

## @param priorityClassName Assign a priority class to pods
priorityClassName: ""

## @param serviceAccount.create Create a service account
## @param serviceAccount.name Name of the service account to create
serviceAccount:
  create: true
  name: "vaultwarden-svc"

## @param podSecurityContext Pod security options
podSecurityContext:
  {}

## @param securityContext Default security options to run vault as read only container without privilege escalation
securityContext:
  {}

## @param dnsConfig Pod DNS options
dnsConfig: {}

extraObjects: []


## @section Reliability configuration

## Liveness probe configuration
livenessProbe:
  enabled: true
  initialDelaySeconds: 5
  timeoutSeconds: 1
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 10
  path: /alive

## Readiness probe configuration
readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  timeoutSeconds: 1
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3
  path: /alive

## @param resources Resource configurations
resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.

## @section Persistent data configuration

storage: 
  existingVolumeClaim: {} 
  data: 
     name: "vaultwarden-data"
     size: "3Gi"
     class: ""
     path: "/data"
     keepPvc: false
     accessMode: "ReadWriteOnce"

## @param webVaultEnabled Enable Web Vault
webVaultEnabled: "true"

## @section Database settings

database:
  type: "default"
  host: ""
  port: ""
  username: ""
  password: ""
  dbName: ""
  uriOverride: ""
  existingSecret: ""
  existingSecretKey: ""
  existingSecretUserKey: username
  existingSecretPasswordKey: password
  connectionRetries: 15
  maxConnections: 10

## @section Push Notifications
## Supported since 1.29.0.
## Refer to https://github.com/dani-garcia/vaultwarden/wiki/Enabling-Mobile-Client-push-notification for details
pushNotifications:
  enabled: false
  existingSecret: ""
  installationId:
    value: ""
    existingSecretKey: ""
  installationKey:
    value: ""
    existingSecretKey: ""
  relayUri: "https://push.bitwarden.com"
  identityUri: "https://identity.bitwarden.com"

## @section Scheduled jobs

## @param emergencyNotifReminderSched Cron schedule of the job that sends expiration reminders to emergency access grantors.
## Set to blank to disable this job.
emergencyNotifReminderSched: "0 3 * * * *"

## @param emergencyRqstTimeoutSched Cron schedule of the job that grants emergency access requests that have met the required wait time.
## Set to blank to disable this job.
emergencyRqstTimeoutSched: "0 7 * * * *"

## @section General settings

## @param domain Domain name where the application is accessed
## Example: https://warden.contoso.com:8443
domain: ""

## @param sendsAllowed Controls whether users are allowed to create Bitwarden Sends.
sendsAllowed: "true"

## @param hibpApiKey HaveIBeenPwned API Key (legacy). Prefer `hibp.value` or `hibp.existingSecret`.
hibpApiKey: ""

## HaveIBeenPwned API Key
hibp:
  existingSecret: ""
  existingSecretKey: ""
  value: ""

## @param trashAutoDeleteDays Number of days to wait before auto-deleting a trashed item.
## If unset (the default), trashed items are not auto-deleted.
## This setting applies globally, so make sure to inform all users of any changes to this setting.
trashAutoDeleteDays: ""

## @param signupsAllowed By default, anyone who can access your instance can register for a new account.
## To disable this, set this parameter to false. Even when signupsAllowed=false, an existing user who is
## an organization owner or admin can still invite new users. If you want to disable this as well, set
## invitationsAllowed to false. The vaultwarden admin can invite anyone via the admin page, regardless
## of any of the restrictions above
## If signupDomains is set, then the value of signupsAllowed is ignored
signupsAllowed: true

## @param signupsVerify Whether to require account verification for newly-registered users.
signupsVerify: "true"

## @param signupDomains List of domain names for users allowed to register. For example:
## example.com,example.net,example.org.
signupDomains: ""

## @param orgEventsEnabled Controls whether event logging is enabled for organizations
orgEventsEnabled: "false"

## @param invitationsAllowed Even when registration is disabled, organization administrators or owners can
## invite users to join organization. After they are invited, they can register with the invited email even
## if signupsAllowed is actually set to false. You can disable this functionality completely by setting
## invitationsAllowed env variable to false
invitationsAllowed: true

## @param invitationOrgName String Name shown in the invitation emails that don't come from a specific organization
invitationOrgName: "Vaultwarden"

## @param invitationExpirationHours The number of hours after which an organization invite token, emergency access invite token,
## email verification token and deletion request token will expire (must be at least 1)
invitationExpirationHours: "120"

## @param emergencyAccessAllowed Controls whether users can enable emergency access to their accounts.
emergencyAccessAllowed: "true"

## @param emailChangeAllowed Controls whether users can change their email.
## This setting applies globally to all users
emailChangeAllowed: "true"

## @param showPassHint Controls whether a password hint should be shown directly in the web page if
## SMTP service is not configured. Not recommended for publicly-accessible instances
## as this provides unauthenticated access to potentially sensitive data.
showPassHint: "false"

## @section Advanced settings

## @param ipHeader Client IP Header, used to identify the IP of the client
ipHeader: "X-Real-IP"

## @param iconService The predefined icon services are: internal, bitwarden, duckduckgo, google.
iconService: "internal"

## @param iconRedirectCode Icon redirect code
iconRedirectCode: "302"

## @param iconBlacklistNonGlobalIps Whether block non-global IPs.
## Useful to secure your internal environment: See https://en.wikipedia.org/wiki/Reserved_IP_addresses for a list of IPs which it will block
iconBlacklistNonGlobalIps: "true"

## @param requireDeviceEmail Require new device emails. When a user logs in an email is required to be sent.
requireDeviceEmail: "false"

## @param extendedLogging Enable extended logging, which shows timestamps and targets in the logs
extendedLogging: "true"

## @param logTimestampFormat Timestamp format used in extended logging.
logTimestampFormat: "%Y-%m-%d %H:%M:%S.%3f"

logging:
  logLevel: ""
  logFile: ""

## Token for the admin interface, preferably an Argon2 PCH string
adminToken:
  existingSecret: ""
  existingSecretKey: ""
  value: "$argon2id$v=19$m=19456,t=2,p=1$Vkx1VkE4RmhDMUhwNm9YVlhPQkVOZk1Yc1duSDdGRVYzd0Y5ZkgwaVg0Yz0$PK+h1ANCbzzmEKaiQfCjWw+hWFaMKvLhG2PjRanH5Kk"

## @section SMTP Configuration
smtp:
  existingSecret: ""
  host: ""
  security: "starttls"
  port: 25
  from: ""
  fromName: ""
  username:
    value: ""
    existingSecretKey: ""
  password:
    value: ""
    existingSecretKey: ""
  authMechanism: "Plain"
  acceptInvalidHostnames: "false"
  acceptInvalidCerts: "false"
  debug: false

## @section Exposure settings

## @param rocket.address Address to bind to
## @param rocket.port Rocket port
## @param rocket.workers Rocket number of workers
rocket:
  address: "0.0.0.0"
  port: "8080"
  workers: "10"

## Service configuration
service:
  type: "ClusterIP"
  annotations: {}
  labels: {}

## Ingress configuration
## Refer to the README for some examples
ingress:
  enabled: true
  class: "traefik"
  additionalAnnotations: {}
  labels: {}
  tls: true
  hostname: "warden.kube.home"
  path: "/"
  pathType: "Prefix"
  tlsSecret: "vaultwarden-tls"


