apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: home-cluster
  namespace: infra-argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/treasuremeasure/Kubernetes-HomeLab
        revision: HEAD
        directories:
          - path: 'my-home-cluster/**'
  template:
    metadata:
      name: '{{ "{{path.basename}}" }}'
    spec:
      project: infra
      source:
        repoURL: https://github.com/treasuremeasure/Kubernetes-HomeLab
        path: '{{ "{{path}}" }}'
        targetRevision: HEAD
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ "{{path.basename}}" }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
