apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-tls
  namespace: app-vault
spec:
  secretName: vault-ha-tls
  duration: 2160h               
  renewBefore: 360h             
  dnsNames:
    - vault.kube.home
    - vault.app-vault.svc.cluster.local
    - vault.app-vault.svc
    - "*.vault-internal.app-vault.svc.cluster.local"
  ipAddresses:
    - 127.0.0.1
  issuerRef:
    name: homelab-ca
    kind: ClusterIssuer
