# cert-manager configuration

global:
  imagePullSecrets: []
  nodeSelector: 
    kubernetes.io/hostname: server
  commonLabels: {}
  priorityClassName: ""

  rbac:
    create: true
    aggregateClusterRoles: true

  logLevel: 2

  leaderElection:
    namespace: "kube-system"

crds:
  enabled: true
  keep: true

# Number of replicas of the cert-manager controller to run
replicaCount: 1

# Maximum number of challenges that can be scheduled as 'processing' at once
maxConcurrentChallenges: 60

imageRegistry: quay.io
imageNamespace: jetstack

image:
  name: cert-manager-controller
  repository: ""
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  automountServiceAccountToken: true

# When this flag is enabled, secrets will be automatically removed when the certificate resource is deleted
enableCertificateOwnerRef: false

resources: {}

securityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true

podLabels: {}

nodeSelector:
  kubernetes.io/os: linux

networkPolicy:
  enabled: false
  ingress:
  - ports:
    - port: http-metrics
      protocol: TCP
    - port: http-healthz
      protocol: TCP
  egress:
  - ports:
    - port: 80
      protocol: TCP
    - port: 443
      protocol: TCP
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP
    - port: 6443
      protocol: TCP

affinity: {}
tolerations: []
topologySpreadConstraints: []

livenessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 15
  successThreshold: 1
  failureThreshold: 8

enableServiceLinks: false

prometheus:
  enabled: true

  servicemonitor:
    enabled: false
    prometheusInstance: default
    targetPort: http-metrics
    path: /metrics
    interval: 60s
    scrapeTimeout: 30s
    labels: {}
    annotations: {}
    honorLabels: false
    endpointAdditionalProperties: {}

  podmonitor:
    enabled: false
    prometheusInstance: default
    path: /metrics
    interval: 60s
    scrapeTimeout: 30s
    labels: {}
    annotations: {}
    honorLabels: false
    endpointAdditionalProperties: {}

webhook:
  replicaCount: 1
  timeoutSeconds: 30

  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true

  podLabels: {}

  validatingWebhookConfiguration:
    namespaceSelector:
      matchExpressions:
        - key: "cert-manager.io/disable-validation"
          operator: "NotIn"
          values:
            - "true"

  mutatingWebhookConfiguration:
    namespaceSelector: {}

  resources: {}

  livenessProbe:
    failureThreshold: 3
    initialDelaySeconds: 60
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1

  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 5
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 1

  nodeSelector:
    kubernetes.io/os: linux

  affinity: {}
  tolerations: []
  topologySpreadConstraints: []

  image:
    name: cert-manager-webhook
    repository: ""
    pullPolicy: IfNotPresent

  serviceAccount:
    create: true
    automountServiceAccountToken: true

  securePort: 10250
  hostNetwork: false
  serviceType: ClusterIP

  networkPolicy:
    enabled: false
    ingress:
    - ports:
      - port: https
        protocol: TCP
      - port: healthcheck
        protocol: TCP
      - port: http-metrics
        protocol: TCP
    egress:
    - ports:
      - port: 80
        protocol: TCP
      - port: 443
        protocol: TCP
      - port: 53
        protocol: TCP
      - port: 53
        protocol: UDP
      - port: 6443
        protocol: TCP

  enableServiceLinks: false

cainjector:
  enabled: true
  replicaCount: 1

  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true

  networkPolicy:
    enabled: false
    ingress:
    - ports:
      - port: http-metrics
        protocol: TCP
    egress:
    - ports:
      - port: 80
        protocol: TCP
      - port: 443
        protocol: TCP
      - port: 53
        protocol: TCP
      - port: 53
        protocol: UDP
      - port: 6443
        protocol: TCP

  resources: {}

  nodeSelector:
    kubernetes.io/os: linux

  affinity: {}
  tolerations: []
  topologySpreadConstraints: []

  podLabels: {}

  image:
    name: cert-manager-cainjector
    repository: ""
    pullPolicy: IfNotPresent

  serviceAccount:
    create: true
    automountServiceAccountToken: true

  enableServiceLinks: false

acmesolver:
  image:
    name: cert-manager-acmesolver
    repository: ""
    pullPolicy: IfNotPresent

startupapicheck:
  enabled: true

  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true

  timeout: 1m
  backoffLimit: 4

  jobAnnotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "1"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded

  extraArgs:
  - -v

  resources: {}

  nodeSelector:
    kubernetes.io/os: linux

  affinity: {}
  tolerations: []

  podLabels: {}

  image:
    name: cert-manager-startupapicheck
    repository: ""
    pullPolicy: IfNotPresent

  rbac:
    annotations:
      helm.sh/hook: post-install
      helm.sh/hook-weight: "-5"
      helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded

  serviceAccount:
    create: true
    annotations:
      helm.sh/hook: post-install
      helm.sh/hook-weight: "-5"
      helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    automountServiceAccountToken: true

  enableServiceLinks: false
